# Generated by Django 6.0.1 on 2026-02-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('sector', models.CharField(db_index=True, max_length=100)),
                ('cooldown_setting', models.IntegerField(db_index=True)),
                ('holding_weeks', models.IntegerField(db_index=True)),
                ('mcap_category', models.CharField(db_index=True, max_length=20)),
                ('breakout_date', models.DateField(db_index=True)),
                ('duration', models.FloatField()),
                ('return_percentage', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['holding_weeks', 'cooldown_setting'], name='analytics_t_holding_2b92cb_idx')],
            },
        ),
    ]
